### ISSUE TITLE
Default images with transparency

### ISSUE THREAD

**Issue by hasecilu** [ttodoshi/dark-firefox-lain-theme#2]
As you can see in the left window, the background color of the image could be different from the one used in the viewport, so in order to have a smooth single bg color I think is best to offer transparent images by default, also in private window the bg is purple and works well.
In the private window the image is not being resized, it would be great it gets resized like in new tab.

![Screenshot from 2022-10-23 09-27-32](https://user-images.githubusercontent.com/53124818/197451893-084766bc-6654-4ab7-a497-2ef0e0a1f11a.png)

**Comment by ttodoshi** [comment]
i think all done

**Comment by hasecilu** [comment]
Hi, actually it was the opposite, as you can see in the video the previous behaviour was to resize the `new tab` image and I think this is ideal, the only drawback was the image was not a `png` one and there was a strip in the middle, that in my opinion don't look very well (previous image).

What I meant to say is: to make the image in the `new private tab` resizable like the one in `new tab`. Last change made both images not resizable which means that in screens with smaller resolution than the image size the image will be cropped (like in the `new private tab`). I think this is preferable to have the automatic resize option.

[Lain_wall.webm](https://user-images.githubusercontent.com/53124818/197634207-129f8479-a574-4539-bfeb-8c015d4075f6.webm)

**Comment by ttodoshi** [comment]
i think now i fixed it in main branch

**Comment by hasecilu** [comment]
Yeah, now I think it's perfect. Thanks!
